export type DataOrder = {
    id: number;
    orderId: string;
    customerName: string,
    serviceType: string,
    status: string,
    timeReceived: Date,
    estimatedCompletion: Date,
    weight: number,
    priority: string,
    specialInstructions: string | null,
    price: string,
};

export const dataOrder: DataOrder[] = [
    {
        id: 1,
        orderId: 'ORD-001',
        customerName: 'John Doe',
        serviceType: 'Wash & Fold',
        status: 'In Progress',
        timeReceived: new Date('2024-09-18 09:30 AM'),
        estimatedCompletion: new Date('2024-09-18 02:30 PM'),
        weight: 5,
        specialInstructions: 'Use hypoallergenic detergent',
        priority: 'Standard',
        price: '$100',
    },
    {
        id: 2,
        orderId: 'ORD-002',
        customerName: 'Jane Smith',
        serviceType: 'Dry Cleaning',
        status: 'Received',
        timeReceived: new Date('2024-09-18 10:15 AM'),
        estimatedCompletion: new Date('2024-09-19 10:15 AM'),
        weight: 2,
        specialInstructions: 'Handle with care, delicate fabric',
        priority: 'Rush',
        price: '$100',
    },
    {
        id: 3,
        orderId: 'ORD-003',
        customerName: 'Emily Johnson',
        serviceType: 'Wash & Iron',
        status: 'In Progress',
        timeReceived: new Date('2024-09-18 11:00 AM'),
        estimatedCompletion: new Date('2024-09-18 05:00 PM'),
        weight: 3.5,
        specialInstructions: 'Starch collars and cuffs',
        priority: 'Standard',
        price: '$100',
    },
    {
        id: 4,
        orderId: 'ORD-004',
        customerName: 'Michael Brown',
        serviceType: 'Alterations',
        status: 'In Progress',
        timeReceived: new Date('2024-09-18 01:30 PM'),
        estimatedCompletion: new Date('2024-09-20 01:30 PM'),
        weight: 1,
        specialInstructions: 'Shorten pants by 2 inches',
        priority: 'Standard',
        price: '$100',
    },
    {
        id: 5,
        orderId: 'ORD-005',
        customerName: 'Sarah Davis',
        serviceType: 'Wash & Fold',
        status: 'Received',
        timeReceived: new Date('2024-09-18 03:45 PM'),
        estimatedCompletion: new Date('2024-09-19 10:45 AM'),
        weight: 7,
        specialInstructions: null,
        priority: 'Rush',
        price: '$100',
    },
]